### ISSUE TITLE
翻譯失效了

### ISSUE THREAD

**Issue by amowu** [zetavg/alfred-google-translate-workflow#1]
![screen shot 2015-04-10 at 1 26 27 pm](https://cloud.githubusercontent.com/assets/559351/7082347/46f5d52a-df85-11e4-9f09-ca2411f5c659.png)

**Comment by vicker** [comment]
Google Translate updated their URLs for translation. Reference http://www.alfredforum.com/topic/120-google-translate-workflow/page-3

**Comment by zetavg** [comment]
Fixed in 76bbad1, thanks for the information!

You can update the script by running `tr update` in Alfred :smiley:

**Comment by Yukaii** [comment]
![2015-04-15 1 23 25](https://cloud.githubusercontent.com/assets/4230968/7142853/0b05b71a-e30e-11e4-90ba-4d88331e56c0.png)

**Comment by vicker** [comment]
Cool. Thanks Neson.

**Comment by amowu** [comment]
@Neson :+1:
