### ISSUE TITLE
複製翻譯後文字的選項未有快捷鍵

### ISSUE THREAD

**Issue by jackblackevo** [zetavg/alfred-google-translate-workflow#4]
您好！
在 Google Translate Workflow 中
複製翻譯後文字選項未有綁定的快捷鍵
雖然可以自行設定
但有預設的鍵值（如：Command）會比較方便
不知是否可再下一版本加入預設的複製翻譯後文字快捷鍵呢？
謝謝您！

**Comment by zetavg** [comment]
咦，我這邊用起來好像預設就有 <kbd>⌘</kbd> + <kbd>1~9</kbd> 的快速鍵 (可以複製並貼上翻譯後的文字) 說？

<img width="694" alt="2017-07-05 9 11 10" src="https://user-images.githubusercontent.com/3784687/27865849-c56a7a3e-6159-11e7-9660-f7eaeda271d3.png">

**Comment by jackblackevo** [comment]
能不能增加一組：⌘ + Enter 複製目前光標所在的翻譯後文字呢？
這樣就可以移到該項後，直接按 Command + Enter 來複製了

**Comment by zetavg** [comment]
其實現在對選到的選項直接按 <kbd>Enter</kbd> 就可以複製 (並自動貼上，如果當下有游標) 了，不知道你可以順利使用嗎？

**Comment by jackblackevo** [comment]
謝謝！原來按下 Enter 就可以了，之前沒有注意到...真是抱歉！
不知可否再請問：「Enter」和「⌘」的小 icon 是如何輸入的呢？

**Comment by zetavg** [comment]
其實是 Markdown (HTML) 語法：`<kbd>Hi</kbd>` → <kbd>Hi</kbd> 這樣 XD

是說剛剛才注意到你的標題是寫「複製 URL」，但我一直回答「複製翻譯後文字」，不知道我們講的是不是同一件事 XD 抱歉。你的 URL 是指？

**Comment by jackblackevo** [comment]
真是不好意思...是我打錯了 XD
我是想說「複製翻譯後文字」沒錯
感謝您的協助！

**Comment by zetavg** [comment]
不會 😄   謝謝你的支持與使用 XD
